### ISSUE TITLE
IE8 bugs

### ISSUE THREAD

**Issue by marianperca** [asual/jquery-format#12]
The latest version doesn't work on IE8. 51/60 tests from http://www.asual.com/jquery/format/test/ fail on IE8

https://www.evernote.com/shard/s51/sh/d2e4624a-294b-4fa1-8a73-e5a53b20d02b/ef6e01f433474059b049436f5a64abe5

**Comment by asual** [comment]
I cannot reproduce this with IE8 and Windows 7. What is the locale of your browser and OS?

**Comment by marianperca** [comment]
I'm running Windows XP on a VM. My locale is english. Here is a more detailed snapshot:
https://www.evernote.com/shard/s51/sh/a4fa4b27-72e2-4291-9179-60d517f3710b/434bbda1a9f64e8b6dbd8da699e6a653

**Comment by asual** [comment]
@marianperca , what was the reason for this issue? Thanks!

**Comment by marianperca** [comment]
This issue appears only in IE in the Win XP virtual machine. I tested the same version of IE on several PC's and it's working fine, no errors. That's good enough for me. I suppose it's something related with the virtual machine I use.
