### ISSUE TITLE
12:00 PM is instead represented as 0:00PM (and 12:00 AM as 0:00AM)

### ISSUE THREAD

**Issue by perchard** [asual/jquery-format#4]
Thanks for the plugin.

Just a small issue - 12:00 PM is instead represented as 0:00PM (and 12:00 AM as 0:00AM).

**Comment by asual** [comment]
How do you achieve the reported results? I just made a few comparisons to the equivalent Java functionality and it works the same.

**Comment by perchard** [comment]
Sorry for not including this in the original issue. I am retrieving a date object via the Google Data API.

```
var startTime = google.gdata.DateTime.fromIso8601(time).getDate();
=> Mon Dec 20 2010 12:00:00 GMT+1030 (CST)
```

I am then formatting the date as follows:

```
var to = $.format.date(startTime, 'K:mm a');
=> 0:00 PM
```

It works as expected with all other dates (i.e. anything other than 12 or 24 hours).

**Comment by asual** [comment]
According to the docs at http://download.oracle.com/javase/1.4.2/docs/api/java/text/SimpleDateFormat.html this should work if you use 'k:mm a' instead of 'K:mm a'.

**Comment by perchard** [comment]
Ah; sorry, I should have read that documentation. Thanks for taking a look at this. I was looking for 'h:mm a'.
